language: php

matrix:
  include:
    - php: 5.4
      env: RENDERER='pug-php/pug:^2.7'
    - php: 5.5
      env: RENDERER='pug-php/pug:^2.7'
    - php: 5.5
      env: RENDERER='pug-php/pug:^3.0'
    - php: 5.5
      env: RENDERER='talesoft/tale-pug:^1.5'
    - php: 5.6
      env: RENDERER='pug-php/pug:^2.7'
    - php: 5.6
      env: RENDERER='pug-php/pug:^3.0'
    - php: 5.6
      env: RENDERER='talesoft/tale-pug:^1.5'
    - php: 7.0
      env: RENDERER='pug-php/pug:^2.7'
    - php: 7.0
      env: RENDERER='pug-php/pug:^3.0'
    - php: 7.1
      env: RENDERER='pug-php/pug:^2.7'
    - php: 7.0
      env: RENDERER='talesoft/tale-pug:^1.5'
    - php: 7.1
      env: RENDERER='pug-php/pug:^3.0'
    - php: 7.2
      env: RENDERER='pug-php/pug:^2.7'
    - php: 7.2
      env: RENDERER='pug-php/pug:^3.0'
    - php: 7.2
      env: RENDERER='talesoft/tale-pug:^1.5'
    - php: 7.3
      env: RENDERER='pug-php/pug:^2.7'
    - php: 7.3
      env: RENDERER='pug-php/pug:^3.0'
    - php: 7.3
      env: RENDERER='talesoft/tale-pug:^1.5'

sudo: false

cache:
  directories:
    - vendor

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer remove pug-php/pug --no-update
  - travis_retry composer require "${RENDERER}" --no-update
  - echo "$(cat composer.json)"
  - travis_retry composer install --prefer-dist --no-interaction

script:
  - vendor/bin/phpunit -c tests/phpunit-travis.xml --verbose --coverage-text --coverage-clover=coverage.xml

after_script:
  - if [[ $RENDERER == "pug-php/pug:^3.0" && ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then vendor/bin/test-reporter --coverage-report coverage.xml; fi;

after_success:
  - if [[ $RENDERER == "pug-php/pug:^3.0" && ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then bash <(curl -s https://codecov.io/bash); fi;

addons:
  code_climate:
    repo_token: 35495c5c91469e666036f0eb22630945ddeeddd13c10745986d7e8be7b83a318
